apiVersion: v1
kind: ConfigMap
metadata:
  name: stealthwebpage
data:
  nginx.conf: |
    user  www-data;
    
    pid /run/nginx.pid;

    worker_processes  auto;

    events {
        worker_connections  1024;
    }

    http {
        keepalive_timeout  65;

        server {
            listen       8080;
            server_name  localhost;

            # proxy the Node app listening on 127.0.0.1:80
            
            location / {
                proxy_pass   http://127.0.0.1:80;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stealthwebpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stealthwebpage
  template:
    metadata:
      labels:
        app: stealthwebpage
    spec:
      containers:

      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
        
      - name: stealthwebpage
        image: rubylegend/node-web-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80

      volumes:
        - name: nginx-conf
          configMap:
            name: stealthwebpage
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: stealthwebpage
spec:
  type: LoadBalancer
  selector:
    app: stealthwebpage
  ports:
  - port: 80
    targetPort: 8080